# Generated by Django 3.2.12 on 2022-03-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.CharField(choices=[('KA', 'Kakao'), ('GO', 'Google')], default='KA', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
