version: "3"

services:
  backend:
    container_name: service_django
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn back.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
  nginx:
    container_name: service_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - static_volume:/data/staticfiles
      - media_volume:/data/media

volumes:
  static_volume:
  media_volume: