# Generated by Django 3.2.12 on 2022-03-10 01:12

import diaries.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=diaries.models.Photo.photo_upload_path)),
                ('dairies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='diaries.dairy')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sumbol', models.CharField(max_length=20)),
                ('dairies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flower', to='diaries.dairy')),
            ],
        ),
    ]
