# Generated by Django 3.2.12 on 2022-03-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dairy',
            new_name='Diary',
        ),
    ]
