# Generated by Django 3.2.12 on 2022-03-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_diary_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='sumbol',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='dairies',
        ),
        migrations.AddField(
            model_name='diary',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='diaries.flower'),
        ),
    ]
