# Generated by Django 3.2.12 on 2022-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_auto_20220324_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
