# Generated by Django 3.2.12 on 2022-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0008_alter_flower_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='custom_content',
            field=models.TextField(null=True),
        ),
    ]
