# Generated by Django 3.2.12 on 2022-03-26 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0009_diary_custom_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
