# Generated by Django 3.2.12 on 2022-03-27 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0011_alter_flower_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='users',
            field=models.ManyToManyField(null=True, related_name='flowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
