# Generated by Django 3.2.12 on 2022-03-31 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0013_auto_20220327_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='content',
            new_name='en_content',
        ),
        migrations.AddField(
            model_name='diary',
            name='ko_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='users',
            field=models.ManyToManyField(related_name='flowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
