# Generated by Django 3.2.12 on 2022-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0014_auto_20220331_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
